import { Copy, MousePointer2, Route, Tag, Trash2 } from 'lucide-react';
import { useMemo, useState } from 'react';
import type { MouseEvent, ReactNode } from 'react';
import type { MapConnection, PremiumMapMarkerAnchor, PremiumMapMetadata, PremiumMapOverlayAnchor, PremiumMapRouteOverlay, RouteDifficulty, RouteStyle } from '../../types';

type AnnotatorMode = 'room' | 'marker' | 'route' | 'select';
type PreviewMode = 'gm' | 'player';
type MarkerType = PremiumMapMarkerAnchor['marker'];

type LocalPremiumMapAsset = {
  id: string;
  name: string;
  url: string;
  width: number;
  height: number;
};

type DraftRoute = {
  id: string;
  from: number;
  to: number;
  type: 'secret';
  points: { xPercent: number; yPercent: number }[];
};

type DraftConnection = {
  id: string;
  from: number;
  to: number;
  type: 'normal' | 'secret';
  routeStyle: RouteStyle;
  routeDifficulty: RouteDifficulty;
  note: string;
};

const localPremiumMapAssets: LocalPremiumMapAsset[] = [
  {
    id: 'premium-test-temple-map',
    name: 'Test Temple Map',
    url: '/premium-maps/test-temple-map.png',
    width: 1254,
    height: 1254,
  },
];

const markerTypes: MarkerType[] = ['treasure', 'hazard', 'objective', 'boss', 'secret', 'custom'];
const routeStyles: RouteStyle[] = ['corridor', 'trail', 'bridge', 'tunnel', 'ledge', 'channel', 'stair', 'crawl', 'servicePath', 'causeway', 'ford', 'grate'];
const routeDifficulties: RouteDifficulty[] = ['clear', 'narrow', 'unstable', 'hidden', 'hazardous', 'blocked'];

function roundPercent(value: number) {
  return Number(value.toFixed(2));
}

function routePath(points: DraftRoute['points']) {
  return points
    .map((point, index) => {
      const x = roundPercent(point.xPercent * 7.2);
      const y = roundPercent(point.yPercent * 4.8);
      return `${index === 0 ? 'M' : 'L'}${x} ${y}`;
    })
    .join(' ');
}

function routePreviewPath(points: DraftRoute['points']) {
  return points
    .map((point, index) => `${index === 0 ? 'M' : 'L'}${point.xPercent} ${point.yPercent}`)
    .join(' ');
}

function createId(prefix: string) {
  return `${prefix}-${Date.now()}-${Math.round(Math.random() * 1000)}`;
}

function copyText(value: string) {
  void navigator.clipboard?.writeText(value);
}

function formatMetadata(asset: LocalPremiumMapAsset, rooms: PremiumMapOverlayAnchor[], markers: PremiumMapMarkerAnchor[], routes: DraftRoute[]) {
  const routeOverlayPaths: PremiumMapRouteOverlay[] = routes
    .filter((route) => route.points.length > 1)
    .map((route) => ({
      from: route.from,
      to: route.to,
      type: 'secret',
      path: routePath(route.points),
    }));

  const gmOverlay = {
    viewBox: '0 0 720 480',
    labelAnchors: rooms,
    markerAnchors: markers,
    routeOverlayPaths,
    notes: 'Generated by the dev-only premium map annotator. Review alignment before committing.',
  };

  const playerOverlay = {
    viewBox: '0 0 720 480',
    labelAnchors: rooms,
  };

  const premiumMap: PremiumMapMetadata = {
    status: 'available',
    baseMapImage: {
      id: asset.id,
      url: asset.url,
      width: asset.width,
      height: asset.height,
      mimeType: 'image/png',
    },
    imageSize: {
      width: asset.width,
      height: asset.height,
    },
    mapBounds: {
      x: 0,
      y: 0,
      width: 720,
      height: 480,
    },
    overlayViewBox: '0 0 720 480',
    printableMapVariant: 'standard',
    showNormalRouteOverlay: false,
    gmOverlay,
    playerOverlay,
    printNotes: 'Generated from the dev-only premium map annotator.',
  };

  return JSON.stringify(premiumMap, null, 2);
}

function formatConnections(connections: DraftConnection[]) {
  const mapConnections: MapConnection[] = connections.map((connection) => ({
    from: connection.from,
    to: connection.to,
    type: connection.type,
    routeStyle: connection.routeStyle,
    routeDifficulty: connection.routeDifficulty,
    ...(connection.note ? { note: connection.note } : {}),
  }));

  return JSON.stringify(
    mapConnections.map((connection) => ({
      from: connection.from,
      to: connection.to,
      type: connection.type,
      routeStyle: connection.routeStyle,
      routeDifficulty: connection.routeDifficulty,
      ...(connection.note ? { note: connection.note } : {}),
    })),
    null,
    2,
  );
}

export function PremiumMapAnnotator() {
  const [assetId, setAssetId] = useState(localPremiumMapAssets[0].id);
  const [mode, setMode] = useState<AnnotatorMode>('room');
  const [previewMode, setPreviewMode] = useState<PreviewMode>('gm');
  const [roomNumber, setRoomNumber] = useState(1);
  const [markerRoomNumber, setMarkerRoomNumber] = useState(1);
  const [markerType, setMarkerType] = useState<MarkerType>('treasure');
  const [customLabel, setCustomLabel] = useState('');
  const [routeFrom, setRouteFrom] = useState(1);
  const [routeTo, setRouteTo] = useState(2);
  const [rooms, setRooms] = useState<PremiumMapOverlayAnchor[]>([]);
  const [markers, setMarkers] = useState<PremiumMapMarkerAnchor[]>([]);
  const [routes, setRoutes] = useState<DraftRoute[]>([]);
  const [activeRouteId, setActiveRouteId] = useState<string | undefined>();
  const [connections, setConnections] = useState<DraftConnection[]>([]);
  const [connectionFrom, setConnectionFrom] = useState(1);
  const [connectionTo, setConnectionTo] = useState(2);
  const [connectionType, setConnectionType] = useState<'normal' | 'secret'>('normal');
  const [connectionRouteStyle, setConnectionRouteStyle] = useState<RouteStyle>('trail');
  const [connectionDifficulty, setConnectionDifficulty] = useState<RouteDifficulty>('clear');
  const [connectionNote, setConnectionNote] = useState('');

  const asset = localPremiumMapAssets.find((item) => item.id === assetId) ?? localPremiumMapAssets[0];
  const metadataOutput = useMemo(() => formatMetadata(asset, rooms, markers, routes), [asset, markers, rooms, routes]);
  const connectionsOutput = useMemo(() => formatConnections(connections), [connections]);
  const activeRoute = routes.find((route) => route.id === activeRouteId);

  const handleMapClick = (event: MouseEvent<SVGSVGElement>) => {
    const svg = event.currentTarget;
    const point = svg.createSVGPoint();
    point.x = event.clientX;
    point.y = event.clientY;
    const transformed = point.matrixTransform(svg.getScreenCTM()?.inverse());
    const xPercent = roundPercent(Math.min(100, Math.max(0, transformed.x)));
    const yPercent = roundPercent(Math.min(100, Math.max(0, transformed.y)));

    if (mode === 'room') {
      setRooms((current) => {
        const next = current.filter((room) => room.roomNumber !== roomNumber);
        return [...next, { roomNumber, xPercent, yPercent }].sort((a, b) => a.roomNumber - b.roomNumber);
      });
      setRoomNumber((current) => current + 1);
    }

    if (mode === 'marker') {
      setMarkers((current) => [
        ...current,
        {
          roomNumber: markerRoomNumber,
          marker: markerType,
          xPercent,
          yPercent,
          ...(markerType === 'custom' && customLabel ? { label: customLabel } : {}),
        },
      ]);
    }

    if (mode === 'route') {
      setRoutes((current) => {
        const existing = current.find((route) => route.id === activeRouteId);
        if (existing) {
          return current.map((route) => (route.id === existing.id ? { ...route, points: [...route.points, { xPercent, yPercent }] } : route));
        }

        const nextRoute = {
          id: createId('route'),
          from: routeFrom,
          to: routeTo,
          type: 'secret' as const,
          points: [{ xPercent, yPercent }],
        };
        setActiveRouteId(nextRoute.id);
        return [...current, nextRoute];
      });
    }
  };

  const addConnection = () => {
    setConnections((current) => [
      ...current,
      {
        id: createId('connection'),
        from: connectionFrom,
        to: connectionTo,
        type: connectionType,
        routeStyle: connectionRouteStyle,
        routeDifficulty: connectionDifficulty,
        note: connectionNote,
      },
    ]);
    setConnectionFrom(connectionTo);
    setConnectionTo(connectionTo + 1);
    setConnectionNote('');
  };

  return (
    <div className="min-h-screen bg-[#17130f] p-4 text-white">
      <div className="mx-auto max-w-7xl">
        <header className="mb-4 rounded-md border border-white/10 bg-white/8 p-4">
          <p className="text-xs font-bold uppercase tracking-[0.18em] text-amber-300">Prototype Dev Tool</p>
          <h1 className="mt-1 font-serif text-3xl font-bold">Premium Map Annotator</h1>
          <p className="mt-2 max-w-3xl text-sm leading-6 text-white/70">
            Dev-only visual helper for placing premium map room anchors, GM markers, secret routes, and draft connections. It outputs pasteable metadata; it does not save files or call a backend.
          </p>
        </header>

        <div className="grid gap-4 lg:grid-cols-[300px_1fr_360px]">
          <aside className="space-y-3 rounded-md border border-white/10 bg-white/8 p-3">
            <label className="block text-xs font-bold uppercase tracking-[0.14em] text-white/50" htmlFor="asset">
              Premium map
            </label>
            <select id="asset" value={assetId} onChange={(event) => setAssetId(event.target.value)} className="w-full rounded-md border border-white/10 bg-black/40 px-3 py-2 text-sm text-white">
              {localPremiumMapAssets.map((item) => (
                <option key={item.id} value={item.id}>
                  {item.name}
                </option>
              ))}
            </select>

            <div>
              <p className="mb-2 text-xs font-bold uppercase tracking-[0.14em] text-white/50">Mode</p>
              <div className="grid grid-cols-2 gap-2">
                <ToolButton active={mode === 'room'} icon={MousePointer2} label="Rooms" onClick={() => setMode('room')} />
                <ToolButton active={mode === 'marker'} icon={Tag} label="Markers" onClick={() => setMode('marker')} />
                <ToolButton active={mode === 'route'} icon={Route} label="Routes" onClick={() => setMode('route')} />
                <ToolButton active={mode === 'select'} icon={Trash2} label="Edit/Delete" onClick={() => setMode('select')} />
              </div>
            </div>

            <div className="rounded-md border border-white/10 bg-black/20 p-3">
              <p className="text-xs font-bold uppercase tracking-[0.14em] text-white/50">Preview</p>
              <div className="mt-2 grid grid-cols-2 gap-2">
                <button type="button" onClick={() => setPreviewMode('gm')} className={`rounded-md px-3 py-2 text-sm font-bold ${previewMode === 'gm' ? 'bg-amber-500 text-black' : 'bg-white/10 text-white'}`}>
                  GM
                </button>
                <button type="button" onClick={() => setPreviewMode('player')} className={`rounded-md px-3 py-2 text-sm font-bold ${previewMode === 'player' ? 'bg-emerald-400 text-black' : 'bg-white/10 text-white'}`}>
                  Player
                </button>
              </div>
            </div>

            {mode === 'room' && (
              <ControlGroup title="Room Anchor">
                <NumberInput label="Room number" value={roomNumber} onChange={setRoomNumber} />
                <p className="text-xs leading-5 text-white/55">Click the map to place or replace this room anchor.</p>
              </ControlGroup>
            )}

            {mode === 'marker' && (
              <ControlGroup title="GM Marker">
                <NumberInput label="Room number" value={markerRoomNumber} onChange={setMarkerRoomNumber} />
                <SelectInput label="Marker" value={markerType} options={markerTypes} onChange={(value) => setMarkerType(value as MarkerType)} />
                {markerType === 'custom' && (
                  <label className="block text-xs font-semibold text-white/70">
                    Custom label
                    <input value={customLabel} onChange={(event) => setCustomLabel(event.target.value)} className="mt-1 w-full rounded-md border border-white/10 bg-black/40 px-2 py-1.5 text-white" />
                  </label>
                )}
              </ControlGroup>
            )}

            {mode === 'route' && (
              <ControlGroup title="Secret Route">
                <div className="grid grid-cols-2 gap-2">
                  <NumberInput label="From" value={routeFrom} onChange={setRouteFrom} />
                  <NumberInput label="To" value={routeTo} onChange={setRouteTo} />
                </div>
                <p className="text-xs leading-5 text-white/55">Click multiple points to draw a GM-only secret route.</p>
                <div className="flex flex-wrap gap-2">
                  <button type="button" onClick={() => setActiveRouteId(undefined)} className="rounded-md bg-white/10 px-2 py-1.5 text-xs font-bold">
                    Finish Route
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      if (!activeRouteId) return;
                      setRoutes((current) => current.map((route) => (route.id === activeRouteId ? { ...route, points: route.points.slice(0, -1) } : route)));
                    }}
                    className="rounded-md bg-white/10 px-2 py-1.5 text-xs font-bold"
                  >
                    Undo Point
                  </button>
                </div>
              </ControlGroup>
            )}

            <ControlGroup title="Draft Connection">
              <div className="grid grid-cols-2 gap-2">
                <NumberInput label="From" value={connectionFrom} onChange={setConnectionFrom} />
                <NumberInput label="To" value={connectionTo} onChange={setConnectionTo} />
              </div>
              <SelectInput label="Type" value={connectionType} options={['normal', 'secret']} onChange={(value) => setConnectionType(value as 'normal' | 'secret')} />
              <SelectInput label="Route style" value={connectionRouteStyle} options={routeStyles} onChange={(value) => setConnectionRouteStyle(value as RouteStyle)} />
              <SelectInput label="Difficulty" value={connectionDifficulty} options={routeDifficulties} onChange={(value) => setConnectionDifficulty(value as RouteDifficulty)} />
              <label className="block text-xs font-semibold text-white/70">
                Note
                <input value={connectionNote} onChange={(event) => setConnectionNote(event.target.value)} className="mt-1 w-full rounded-md border border-white/10 bg-black/40 px-2 py-1.5 text-white" />
              </label>
              <button type="button" onClick={addConnection} className="w-full rounded-md bg-amber-500 px-3 py-2 text-sm font-bold text-black">
                Add Connection
              </button>
            </ControlGroup>
          </aside>

          <main className="rounded-md border border-white/10 bg-black/25 p-3">
            <div className="mb-2 flex items-center justify-between gap-3 text-xs font-semibold text-white/55">
              <span>{asset.url}</span>
              <span>{activeRoute ? `Drawing route ${activeRoute.from}-${activeRoute.to}` : 'Click the map to annotate'}</span>
            </div>
            <svg viewBox="0 0 100 100" role="img" aria-label="Premium map annotation canvas" onClick={handleMapClick} className="h-auto w-full cursor-crosshair rounded-md border border-white/10 bg-black">
              <image href={asset.url} x="0" y="0" width="100" height="100" preserveAspectRatio="xMidYMid slice" />

              {previewMode === 'gm' &&
                routes.map((route) => (
                  <g key={route.id}>
                    {route.points.length > 1 && <path d={routePreviewPath(route.points)} fill="none" stroke="#f59e0b" strokeDasharray="1.8 1.4" strokeLinecap="round" strokeLinejoin="round" strokeWidth="0.75" />}
                    {route.points.map((point, index) => (
                      <circle key={`${route.id}-${index}`} cx={point.xPercent} cy={point.yPercent} r="0.9" fill="#fef3c7" stroke="#92400e" strokeWidth="0.25" />
                    ))}
                  </g>
                ))}

              {previewMode === 'gm' &&
                markers.map((marker, index) => (
                  <g key={`${marker.roomNumber}-${marker.marker}-${index}`}>
                    <circle cx={marker.xPercent} cy={marker.yPercent} r="2.1" fill="#fff8e8" stroke="#92400e" strokeWidth="0.5" />
                    <text x={marker.xPercent} y={(marker.yPercent ?? 0) + 0.9} textAnchor="middle" fontSize="2.1" fontWeight="900" fill="#7c2d12">
                      {(marker.label ?? marker.marker.slice(0, 1)).toUpperCase()}
                    </text>
                  </g>
                ))}

              {rooms.map((room) => (
                <g key={room.roomNumber}>
                  <rect x={(room.xPercent ?? 0) - 2.2} y={(room.yPercent ?? 0) - 2.2} width="4.4" height="4.4" rx="1" fill="#fff8e8" opacity="0.96" />
                  <text x={room.xPercent} y={(room.yPercent ?? 0) + 1.3} textAnchor="middle" fontSize="3.3" fontWeight="900" fill="#211a16">
                    {room.roomNumber}
                  </text>
                </g>
              ))}
            </svg>
          </main>

          <aside className="space-y-3">
            <AnnotationList title="Rooms" emptyText="No room anchors yet.">
              {rooms.map((room) => (
                <ListRow key={room.roomNumber} label={`Room ${room.roomNumber}`} detail={`${room.xPercent}, ${room.yPercent}`} onDelete={() => setRooms((current) => current.filter((item) => item.roomNumber !== room.roomNumber))} />
              ))}
            </AnnotationList>

            <AnnotationList title="GM Markers" emptyText="No GM markers yet.">
              {markers.map((marker, index) => (
                <ListRow key={`${marker.roomNumber}-${marker.marker}-${index}`} label={`${marker.marker} in Room ${marker.roomNumber}`} detail={`${marker.xPercent}, ${marker.yPercent}`} onDelete={() => setMarkers((current) => current.filter((_, itemIndex) => itemIndex !== index))} />
              ))}
            </AnnotationList>

            <AnnotationList title="Secret Routes" emptyText="No secret routes yet.">
              {routes.map((route) => (
                <ListRow key={route.id} label={`Room ${route.from} to ${route.to}`} detail={`${route.points.length} point${route.points.length === 1 ? '' : 's'}`} onDelete={() => setRoutes((current) => current.filter((item) => item.id !== route.id))} />
              ))}
            </AnnotationList>

            <AnnotationList title="Connections" emptyText="No draft connections yet.">
              {connections.map((connection) => (
                <ListRow key={connection.id} label={`${connection.from}-${connection.to} ${connection.type}`} detail={`${connection.routeStyle}, ${connection.routeDifficulty}`} onDelete={() => setConnections((current) => current.filter((item) => item.id !== connection.id))} />
              ))}
            </AnnotationList>

            <OutputBox title="premiumMap metadata" value={metadataOutput} />
            <OutputBox title="map.connections draft" value={connectionsOutput} />
          </aside>
        </div>
      </div>
    </div>
  );
}

function ToolButton({ active, icon: Icon, label, onClick }: { active: boolean; icon: typeof MousePointer2; label: string; onClick: () => void }) {
  return (
    <button type="button" onClick={onClick} className={`flex items-center justify-center gap-2 rounded-md px-2 py-2 text-xs font-bold ${active ? 'bg-amber-500 text-black' : 'bg-white/10 text-white hover:bg-white/15'}`}>
      <Icon className="h-4 w-4" aria-hidden="true" />
      {label}
    </button>
  );
}

function ControlGroup({ title, children }: { title: string; children: ReactNode }) {
  return (
    <div className="space-y-2 rounded-md border border-white/10 bg-black/20 p-3">
      <p className="text-xs font-bold uppercase tracking-[0.14em] text-white/50">{title}</p>
      {children}
    </div>
  );
}

function NumberInput({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) {
  return (
    <label className="block text-xs font-semibold text-white/70">
      {label}
      <input type="number" min="1" value={value} onChange={(event) => onChange(Number(event.target.value))} className="mt-1 w-full rounded-md border border-white/10 bg-black/40 px-2 py-1.5 text-white" />
    </label>
  );
}

function SelectInput({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) {
  return (
    <label className="block text-xs font-semibold text-white/70">
      {label}
      <select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full rounded-md border border-white/10 bg-black/40 px-2 py-1.5 text-white">
        {options.map((option) => (
          <option key={option} value={option}>
            {option}
          </option>
        ))}
      </select>
    </label>
  );
}

function AnnotationList({ title, emptyText, children }: { title: string; emptyText: string; children: ReactNode }) {
  return (
    <section className="rounded-md border border-white/10 bg-white/8 p-3">
      <h2 className="text-sm font-black uppercase tracking-[0.12em] text-white/70">{title}</h2>
      <div className="mt-2 space-y-2">{children || <p className="text-xs text-white/45">{emptyText}</p>}</div>
    </section>
  );
}

function ListRow({ label, detail, onDelete }: { label: string; detail: string; onDelete: () => void }) {
  return (
    <div className="flex items-center justify-between gap-2 rounded-md bg-black/25 px-2 py-1.5 text-xs">
      <div>
        <p className="font-bold text-white">{label}</p>
        <p className="text-white/45">{detail}</p>
      </div>
      <button type="button" onClick={onDelete} className="rounded bg-white/10 p-1 text-white/70 hover:text-white" aria-label={`Delete ${label}`}>
        <Trash2 className="h-3.5 w-3.5" aria-hidden="true" />
      </button>
    </div>
  );
}

function OutputBox({ title, value }: { title: string; value: string }) {
  return (
    <section className="rounded-md border border-white/10 bg-white/8 p-3">
      <div className="flex items-center justify-between gap-2">
        <h2 className="text-sm font-black uppercase tracking-[0.12em] text-white/70">{title}</h2>
        <button type="button" onClick={() => copyText(value)} className="inline-flex items-center gap-1 rounded-md bg-amber-500 px-2 py-1 text-xs font-bold text-black">
          <Copy className="h-3.5 w-3.5" aria-hidden="true" />
          Copy
        </button>
      </div>
      <textarea readOnly value={value} className="mt-2 h-56 w-full resize-y rounded-md border border-white/10 bg-black/50 p-2 font-mono text-xs leading-5 text-white/75" />
    </section>
  );
}
